name: coincap_list
description: CoinCap API Assets list
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  dio: ^5.8.0+1
  flutter_riverpod: ^3.0.0-dev.17
  riverpod_annotation: ^3.0.0-dev.17
  envied: ^1.1.1
  shimmer: ^3.0.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.4
  riverpod_generator: ^3.0.0-dev.17
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  envied_generator: ^1.1.1
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: SFProSemibold
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Semibold.otf